# Generated by Django 3.1.7 on 2021-04-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210423_0216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
