# Generated by Django 3.1.7 on 2021-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210428_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
