# Generated by Django 3.1.7 on 2021-04-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project'),
        ),
    ]
